# Generated by Django 5.1.1 on 2024-09-11 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vuelo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Nacional", "Nacional"),
                            ("Nacional", "Internacional"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "precio",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
            ],
        ),
    ]
